#ifndef __REGISTERFLAGS_H__
#define __REGISTERFLAGS_H__

enum class RegisterFlags
{
    FLAGS_NONE,
    FLAGS_ERR_SYSCALL_OUT_OF_RANGE,
    FLAGS_ERR_LOCATION_FORMAT_UNSUPPORTED,
    FLAGS_ERR_LOCATION_REGISTER_OUT_OF_RANGE,
};

#endif //__REGISTERFLAGS_H__
